name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: cd ./backend && npm i
      - run: cd ./backend && npm run test:e2e

      - name: Build the Docker image
        run: cd ./backend && docker build . --file Dockerfile --tag docker.io/padi2312/imagedb-backend:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/padi2312/imagedb-backend:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
